version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  create-small-cluster:
    docker:
      - image: "cimg/python:3.10"
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - aws-eks/install-aws-iam-authenticator:
          release-tag: ""
      - aws-eks/create-cluster:
          cluster-name: << parameters.cluster-name >>
          skip-kubectl-install: false
          verbose: 3
          aws-region: us-east-1a
          node-type: t2.small
          nodes-max: 2
          ssh-access: false
          ssh-public-key: ""
  create-deployment:
    docker:
      - image: "cimg/python:3.10"
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.yml
          resource-name: deployment/blue
  create-service:
    docker:
      - image: "cimg/python:3.10"
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          resource-file-path: service.yml
          resource-name: service/bluegreenlb

workflows:
  deployment:
    jobs:
      - create-small-cluster:
          cluster-name: eks-demo-deployment
      - create-service:
          cluster-name: eks-demo-deployment
          requires:
            - create-small-cluster
      - create-deployment:
          cluster-name: eks-demo-deployment
          requires:
            - create-service
      - aws-eks/update-container-image:
          cluster-name: eks-demo-deployment
          container-image-updates: "blue=binh/testblueimage:latest"
          record: true
          requires:
            - create-deployment
          resource-name: deployment/blue
